package com.anilazahid.quiz;

import android.app.AlertDialog;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.*;
import androidx.recyclerview.widget.*;
import com.google.firebase.database.*;
import java.util.*;

public class AdminQuestionsActivity extends AdminBaseActivity {
    private final List<DataSnapshot> categories=new ArrayList<>(), questions=new ArrayList<>(); private Spinner category; private QAdapter adapter; private String selectedCategory;
    @Override protected void onCreate(Bundle s){super.onCreate(s);setContentView(R.layout.activity_admin_list);((TextView)findViewById(R.id.adminListTitle)).setText("QUESTIONS");findViewById(R.id.adminListSearch).setVisibility(android.view.View.GONE);findViewById(R.id.adminListBack).setOnClickListener(v->finish());category=new Spinner(this);((LinearLayout)findViewById(R.id.adminListTitle).getParent()).addView(category,0,new LinearLayout.LayoutParams(0,48,1));RecyclerView r=findViewById(R.id.adminRecycler);r.setLayoutManager(new LinearLayoutManager(this));adapter=new QAdapter();r.setAdapter(adapter);findViewById(R.id.adminListAdd).setOnClickListener(v->edit(null));requireAdmin(this::loadCategories);}
    private void loadCategories(){db.child("quick_categories").addListenerForSingleValueEvent(new ValueEventListener(){public void onDataChange(DataSnapshot s){categories.clear();List<String> names=new ArrayList<>();for(DataSnapshot x:s.getChildren()){categories.add(x);names.add(x.child("title").getValue(String.class));}category.setAdapter(new ArrayAdapter<String>(AdminQuestionsActivity.this,android.R.layout.simple_spinner_dropdown_item,names));category.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,android.view.View v,int pos,long id){if(pos<categories.size()){selectedCategory=categories.get(pos).getKey();loadQuestions();}}});}public void onCancelled(DatabaseError e){toast("Could not load categories.");}});}
    private void loadQuestions(){questions.clear();if(selectedCategory!=null)db.child("quick_categories").child(selectedCategory).child("questions").addListenerForSingleValueEvent(new ValueEventListener(){public void onDataChange(DataSnapshot s){for(DataSnapshot x:s.getChildren())questions.add(x);adapter.notifyDataSetChanged();}public void onCancelled(DatabaseError e){}});}
    private EditText field(LinearLayout b,String hint){EditText e=new EditText(this);e.setHint(hint);b.addView(e);return e;}
    private void edit(DataSnapshot old){if(selectedCategory==null){toast("Add a category first.");return;}LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(24,0,24,0);EditText q=field(b,"Question text *"),a=field(b,"Option A *"),bb=field(b,"Option B *"),c=field(b,"Option C *"),d=field(b,"Option D *"),ex=field(b,"Explanation (optional)"),dif=field(b,"Difficulty (optional)");Spinner answer=new Spinner(this);answer.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Correct: A","Correct: B","Correct: C","Correct: D"}));b.addView(answer,5);if(old!=null){q.setText(old.child("q").getValue(String.class));a.setText(old.child("opt1").getValue(String.class));bb.setText(old.child("opt2").getValue(String.class));c.setText(old.child("opt3").getValue(String.class));d.setText(old.child("opt4").getValue(String.class));ex.setText(old.child("explanation").getValue(String.class));dif.setText(old.child("difficulty").getValue(String.class));Long idx=old.child("ansIdx").getValue(Long.class);answer.setSelection(idx==null?0:idx.intValue());}new AlertDialog.Builder(this).setTitle(old==null?"Add question":"Edit question").setView(b).setNegativeButton("CANCEL",null).setPositiveButton("SAVE",(dialog,w)->{String[] values={q.getText().toString().trim(),a.getText().toString().trim(),bb.getText().toString().trim(),c.getText().toString().trim(),d.getText().toString().trim()};for(String value:values)if(value.isEmpty()){toast("All question and option fields are required.");return;}DatabaseReference ref=old==null?db.child("quick_categories").child(selectedCategory).child("questions").push():db.child("quick_categories").child(selectedCategory).child("questions").child(old.getKey());int answerIndex=answer.getSelectedItemPosition();Map<String,Object> data=new HashMap<>();data.put("q",values[0]);data.put("opt1",values[1]);data.put("opt2",values[2]);data.put("opt3",values[3]);data.put("opt4",values[4]);data.put("ansIdx",answerIndex);data.put("correctAnswer",String.valueOf((char)('A'+answerIndex)));data.put("points",10);data.put("explanation",ex.getText().toString().trim());data.put("difficulty",dif.getText().toString().trim());ref.updateChildren(data);}).show();}
    private class QAdapter extends RecyclerView.Adapter<QAdapter.H>{public H onCreateViewHolder(ViewGroup p,int t){TextView v=new TextView(AdminQuestionsActivity.this);v.setTextColor(0xffffffff);v.setTextSize(15);v.setPadding(18,18,18,18);v.setBackgroundResource(R.drawable.bg_card);return new H(v);}public void onBindViewHolder(H h,int i){DataSnapshot s=questions.get(i);String answer=s.child("correctAnswer").getValue(String.class);if(answer==null){Long index=s.child("ansIdx").getValue(Long.class);answer=index==null?"A":String.valueOf((char)('A'+index));}h.v.setText(s.child("q").getValue(String.class)+"\nCorrect: "+answer);h.v.setOnClickListener(v->new AlertDialog.Builder(AdminQuestionsActivity.this).setItems(new String[]{"Edit","Delete"},(d,w)->{if(w==0)edit(s);else new AlertDialog.Builder(AdminQuestionsActivity.this).setTitle("Delete question?").setNegativeButton("CANCEL",null).setPositiveButton("DELETE",(x,y)->db.child("quick_categories").child(selectedCategory).child("questions").child(s.getKey()).removeValue()).show();}).show());}public int getItemCount(){return questions.size();}class H extends RecyclerView.ViewHolder{TextView v;H(TextView x){super(x);v=x;}}}
}